language: node_js
node_js: node
cache:
  directories:
  - node_modules
script:
- npm test
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: d5Ne1Sa0tLnyVxUWoez/nPfvvrjN3LqE60M7D6SOSlulI6gvCgeakHNvfKnEGS5sGPY8eAcaEErh1yWMz/ubc/j6jZrhTLahgpJN21Ttin9rPhwQH+ZpNMfHCIZaHak171RTkZeBuEk9qrdw2LUZg+PX8IITT71ODl3JL3y0cXXZ878Kbz9FNtfi2zu92ohk8iX+3dNOd+WsND1dozNIL55y6o5iLdTmGyLOklrqTkEz1JfwECGncgLqwRUl8CPvGtLjP/H9suBYWjFyV3R+wqBfQsDYCgqrOAG6T7tfWYYqki7IeXvE2H7n1r7aU/wLaMtFl2CjGGrjke4tL63btprkVD9LFVzRjxYYtSVzHTTM754Yj+rrOtOLImDusNIHRLrNerukao2GXlVYBCaLQvOzG/P6jsVTAYUZiW2AF+0GBvceUq1U3qZM7rU1OgBMvgRDRKXij5AE0jTxRrrLIQa6Ilg1zInsFl+CYsNHIamUuRZfILO2XfDcCKeRlszYgzeLFOhWMLRvtDYUHVAv/MQteVPOXTF8mVVzcBrIFCiF3fMGUKGYJI7Ou8mcYYx+4BOUySvBB8O5xlNmre7HD1BNN5CaQ8awDMNXyMyUzq0OXcT5ZvQQQyVjDwDVVcWFcPGD1pTloavP1hY8D0Wy/rOy6B+Yz1EJG+aJkIp984A=
  app: summer-bucket-app
  on:
    repo: jiehan1029/summer-bucket-app
